version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: my_postgres_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo
    environment:
      - DATABASE_URL=postgres://postgres_user:postgres_password@db:5432/my_postgres_db

volumes:
  postgres_data:
  mongo_data:
